- name: "Pre-check Visual Studio Professional 2015"
  win_shell: Get-ItemProperty 'HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*' | Where-Object {$_.DisplayName -eq "Microsoft Visual Studio Professional 2015 with Updates"} | Select-Object -ExpandProperty ModifyPath
  register: modify_cmd
  ignore_errors: true
  when: not win_vs2015_force_install

- name: "Pre-check"
  debug:
    msg: "VS2015 already installed. No need to run"
  when: not win_vs2015_force_install and (modify_cmd.stdout | length > 0)

- name: "INSTALL Visual Studio Professional 2015"
  include_tasks: install.yml
  when: win_vs2015_force_install or (modify_cmd.stdout | length == 0)
