---
- name: Add runtime user to "Log on as a service" policiy
  win_user_right:
    name: SeServiceLogonRight
    users:
      - "{{ win_jenkins_service.username }}"
    action: add
  ignore_errors: true

- name: "Setup Service logon"
  win_service:
    name: "{{ service_name }}"
    state: restarted
    username: "{{ win_jenkins_service.username }}"
    password: "{{ win_jenkins_service.password }}"
    update_password: always

- name: "Setup Service logon for JET"
  win_service:
    name: "{{ service_name_jet }}"
    state: restarted
    username: "{{ win_jenkins_service.username }}"
    password: "{{ win_jenkins_service.password }}"
    update_password: always
  when: service_name_jet is defined

- name: "Setup Service logon for DEV"
  win_service:
    name: "{{ service_name_dev }}"
    state: restarted
    username: "{{ win_jenkins_service.username }}"
    password: "{{ win_jenkins_service.password }}"
    update_password: always
  when: service_name_dev is defined
