---
- set_fact:
    user_dir: "C:\\Users\\{{ win_git_user.username }}"

- name: "Add .ssh directory"
  win_file:
    path: "{{ user_dir }}\\.ssh"
    state: directory

- name: "Add private key for user {{ win_git_user.username }}"
  win_template:
    dest: "{{ user_dir }}\\.ssh\\id_rsa"
    src: ../templates/id_rsa.j2

- name: "Add public key for user {{ win_git_user.username }}"
  win_template:
    dest: "{{ user_dir }}\\.ssh\\id_rsa.pub"
    src: ../templates/id_rsa.pub.j2

- name: "Add known_hosts for user {{ git_user }}"
  template:
    dest: "{{ user_dir }}\\.ssh\\known_hosts"
    src: ../templates/known_hosts.j2
