- name: "Setup temp folder for software download"
  win_file:
    state: directory
    path: "{{ win_vs2019_temp_dir }}"

- name: "Download vs2019 exe"
  win_get_url:
    url: "{{ win_vs2019_installer_location }}{{ win_vs2019_package_name }}"
    dest: "{{ win_vs2019_temp_dir }}\\{{ win_vs2019_package_name }}"
  retries: 2
  delay: 5
  register: result
  until: result is succeeded

- name: "Install Visual Studio Professional 2019"
  win_command: "{{ win_vs2019_temp_dir }}\\{{ win_vs2019_package_name }}
    --installPath \"{{ win_vs2019_install_dir }}\" --quiet --norestart
    --add Microsoft.VisualStudio.Component.CoreEditor
    --add Microsoft.VisualStudio.Workload.CoreEditor
    --add Microsoft.VisualStudio.Component.NuGet
    --add Microsoft.VisualStudio.Component.Roslyn.Compiler
    --add Microsoft.Component.MSBuild
    --add Microsoft.VisualStudio.Component.TextTemplating
    --add Microsoft.VisualStudio.Component.VC.CoreIde
    --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64
    --add Microsoft.VisualStudio.Component.Graphics.Tools
    --add Microsoft.VisualStudio.Component.Windows10SDK.19041
    --add Microsoft.VisualStudio.Component.VC.Redist.14.Latest
    --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core
    --add Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions.CMake
    --add Microsoft.VisualStudio.Component.VC.CMake.Project
    --add Microsoft.VisualStudio.Component.VC.ATL
    --add Microsoft.VisualStudio.Component.VC.TestAdapterForBoostTest
    --add Microsoft.VisualStudio.Component.VC.TestAdapterForGoogleTest
    --add Microsoft.VisualStudio.Component.VC.ASAN
    --add Microsoft.VisualStudio.Component.VC.v141.x86.x64
    --add Microsoft.VisualStudio.Component.Debugger.JustInTime
    --add Microsoft.VisualStudio.Workload.NativeDesktop
    --wait --downloadThenInstall"
  args:
    creates: "{{ win_vs2019_install_dir }}"

- name: "Cleanup temp download folder"
  win_file:
    state: absent
    path: "{{ win_vs2019_temp_dir }}"
