- name: "Setup temp folder for canape setup files"
  win_file:
    state: directory
    path: "{{ win_canape_temp_dir }}"

- name: "Create canape Program directory"
  win_file:
    state: directory
    path: "{{ win_canape_install_dir }}"

- name: "Download canape install file"
  win_get_url:
    url: "{{ win_canape_package_location }}/{{ win_canape_package_version }}.zip"
    dest: "{{ win_canape_temp_dir }}\\{{ win_canape_package_version }}.zip"
  retries: 2
  delay: 2
  register: result
  until: result is succeeded

- name: "Unpack canape"
  win_unzip:
    src: "{{ win_canape_temp_dir }}\\{{ win_canape_package_version }}.zip"
    dest: "{{ win_canape_temp_dir }}"

- name: "Install canape"
  win_package:
    path: "{{ win_canape_temp_dir }}\\Setup.exe"
    arguments:
      - /s /v/qn
      - /VPROGRAM_LANGUAGE=01
      - /REGKIND=2

- name: "Cleanup temp download folder"
  win_file:
    state: absent
    path: "{{ win_canape_temp_dir }}"
