---
- name: "Handle NRCS Windows worker nodes"
  hosts: nrcs_win_worker
  gather_facts: false

  roles:
# Pre agent configuration
    - role: set_jenkins_home
    - role: disable_standby
    - role: add_remote_user
# Tool Installers
    - role: had.win_7z
    - role: had.win_adtf
    - role: had.win_anaconda
    - role: had.win_ffmpeg
    - role: had.win_git
    - role: had.win_ibeo_client
    - role: had.win_java
    - role: had.win_nssm
    - role: had.win_pcl
    - role: had.win_python
    - role: had.win_qt
    - role: had.win_tcc
    - role: had.win_vs2010
    - role: had.win_vs2015
    - role: had.win_jenkins-master-add-node
    - role: had.win_jenkins-worker
# Post agent configuration
    - role: checkout_git_repo
      vars:
        source_url: "ssh://git@sourcecode01.de.bosch.com:7999/nrcsgen2/fml_development.git"
        checkout_dir: "{{ jenkins_home }}\\0"
        branch_name: "master"
    - role: checkout_git_repo
      vars:
        source_url: "ssh://git@sourcecode01.de.bosch.com:7999/nrcsgen2/nrc20.git"
        checkout_dir: "{{ jenkins_home }}\\0\\nrc2"
        branch_name: "develop"
    - role: run_additional_commands
    - role: restart_jenkins_service
    - role: copy_jenkins_executor_directory
