- name: Ensure local certs directory exists
  file:
    state: directory
    path: "/etc/pki/ca-trust/source/anchors"
  check_mode: false

- name: Enabling the system shared CA store
  command: update-ca-trust enable
  become: true
  changed_when: true

- name: Download Bosch certificates
  get_url:
    url: "{{ ca_store }}/{{ item }}.crt"
    dest: "/etc/pki/ca-trust/source/anchors"
  with_items: "{{ ca_list }}"
  become: true

- name: Updating the system CA store
  command: update-ca-trust extract
  become: true
  register: update_result
  changed_when: update_result.stdout is not search("0 added, 0 removed")
