- name: Enable long path support on Windows
  ansible.windows.win_powershell:
    script: |
      New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
