- name: "restart sshd to reflect changes to PATH"
  win_shell: "Restart-Service -Name sshd"
  async: 60
  poll: 0
  register: sshd_restart

- name: "wait for connectivity to be resumed after sshd restart"
  async_status:
    jid: "{{ sshd_restart.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 60
  delay: 1
  ignore_errors: true

- name: "Reset ssh connection"
  include_tasks: "reset_ssh.yml"
  when: job_result is succeeded
