- name: Prepare and install
  block:
    - name: "Include OS specific variables"
      include_vars: "vars/{{ ansible_os_family }}.yml"

    - name: "Create tmp dir for install files"
      file:
        path: "{{ dockerce_install_dir }}"
        state: directory

    - name: "Run installer"
      include_tasks: "os/{{ ansible_os_family }}.yml"
      when: upgrade_docker or which_dockerd.failed
  always:
    - name: "Cleanup"
      file:
        path: "{{ dockerce_install_dir }}"
        state: absent
