- name: Get Windows version
  win_file_version:
    path: C:\Windows\System32\hal.dll
  register: hal_dll_version_return

- name: Windows is post 1709
  set_fact:
    windows_version: "post-1709"
  when: hal_dll_version_return.win_file_version.file_build_part >= "16299"

- name: Windows is pre 1709
  set_fact:
    windows_version: "pre-1709"
  when: hal_dll_version_return.win_file_version.file_build_part < "16299"

- name: Fail, if Windows Build number does not support Windows Docker Containers correctly
  fail:
    msg: "Windows Build Number {{hal_dll_version_return.win_file_version.product_version}} doesn´t support Windows Docker Container correctly ({{hal_dll_version_return.win_file_version.file_private_part}} is to small)"
  when: (windows_version == "pre-1709") and
        (hal_dll_version_return.win_file_version.file_private_part|int < 206)

- name: Congratulations
  debug:
    msg: "With your Build Number {{hal_dll_version_return.win_file_version.product_version}} you have choosen a good basis for Windows Docker Containers!"
