- name: Checking if Docker Windows Service is already configured (to always ensure a fresh Windows Docker installation)
  win_service:
    name: docker
  register: docker_service_info
  ignore_errors: true

- name: Stop old Docker Windows Service if there
  win_service:
    name: docker
    state: stopped
  when: docker_service_info.exists

- name: Remove old Docker Windows Service if there via NSSM
  no_log: true
  win_nssm:
    name: docker
    state: absent

- name: Install (or upgrade) Docker via chocolatey
  win_chocolatey:
    name: docker-engine
    state: latest
    proxy_url: "{{ proxy_url }}"
    proxy_username: "{{ proxy_username }}"
    proxy_password: "{{ proxy_password }}"

- name: Install and start service via NSSM
  no_log: true
  win_nssm:
    name: docker
    application: "C:\\ProgramData\\chocolatey\\lib\\docker-engine\\tools\\docker\\dockerd.exe"
    state: started
