- name: Install (or upgrade) Docker Compose via chocolatey
  win_chocolatey:
    name: docker-compose
    state: latest
    proxy_url: "{{ proxy_url }}"
    proxy_username: "{{ proxy_username }}"
    proxy_password: "{{ proxy_password }}"
